commit238

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,7 @@
 ############################### NEW ################################
 name: Relis
 
-on: 
+on:
   push:
     branches:
       - main
@@ -39,10 +39,10 @@ jobs:
           git config user.name $GITHUB_ACTOR
           # Retrieve the commit hash from the file
           last_successful_commit=$(cat successful_commit.txt)
-          
+        
           # Reset the branch to the last successful commit
           #git clone https://github.com/$GITHUB_ACTOR/relis_demo_test.git
-          git reset --hard '977079e05b126b8b862181dadf2b13328e8edfe1'
+          git reset
 
           # git revert -n $last_successful_commit
           # git commit -m "Revert"
@@ -68,52 +68,49 @@ jobs:
           # git show last_successful_commit
           # 3200e6ab353824bbc3919236ee432b78598afbb3
 
-
-
-
 ###
-      # - name: Build Docker Image
-      #   run: docker-compose build
-      #   working-directory: relis_deployment
+# - name: Build Docker Image
+#   run: docker-compose build
+#   working-directory: relis_deployment
 
-      # - name: Run Docker Containers
-      #   run: docker-compose up -d
-      #   working-directory: relis_deployment
+# - name: Run Docker Containers
+#   run: docker-compose up -d
+#   working-directory: relis_deployment
 
-      # - name: Wait for Application to Start
-      #   run: sleep 10
+# - name: Wait for Application to Start
+#   run: sleep 10
 
-      # - name: Set relis-app Container permission
-      #   run: |
-      #     docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
+# - name: Set relis-app Container permission
+#   run: |
+#     docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
 
-      # - name: Run Unit test
-      #   run: |
-      #     response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
-      #     echo $response
-    
-      #     if [ "$response" == "successful" ]; then
-      #       echo "The unit test passed. Proceeding with the workflow."
-      #       echo $GITHUB_SHA > successful_commit.txt
+# - name: Run Unit test
+#   run: |
+#     response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
+#     echo $response
 
-      #     elif [ "$response" == "failed" ]; then
-      #       echo "The unit test failed. Reverting to the last successful commit."
+#     if [ "$response" == "successful" ]; then
+#       echo "The unit test passed. Proceeding with the workflow."
+#       echo $GITHUB_SHA > successful_commit.txt
 
-      #       # Retrieve the commit hash from the file
-      #       last_successful_commit=$(cat successful_commit.txt)
+#     elif [ "$response" == "failed" ]; then
+#       echo "The unit test failed. Reverting to the last successful commit."
 
-      #       # Reset the branch to the last successful commit
-      #       git reset --hard $last_successful_commit
+#       # Retrieve the commit hash from the file
+#       last_successful_commit=$(cat successful_commit.txt)
 
-      #       # Force push to update the branch on the remote repository
-      #       git push --force
+#       # Reset the branch to the last successful commit
+#       git reset --hard $last_successful_commit
 
-      #       exit 1
+#       # Force push to update the branch on the remote repository
+#       git push --force
 
-      #     else
-      #       echo "The unit test has an error"
-      #       exit 1
-      #     fi
+#       exit 1
 
-      # - name: Stop all running Docker Containers
-      #   run: docker stop $(docker ps -q)
+#     else
+#       echo "The unit test has an error"
+#       exit 1
+#     fi
+
+# - name: Stop all running Docker Containers
+#   run: docker stop $(docker ps -q)
