commit500

diff --git a/.github/workflows/relis_unit_test.yml b/.github/workflows/relis_unit_test.yml
--- a/.github/workflows/relis_unit_test.yml
+++ b/.github/workflows/relis_unit_test.yml
@@ -6,20 +6,6 @@ on:
     branches:
       - main
 
-# permissions: write-all
-  # actions: write
-  # contents: write
-  # checks: write
-  # deployments: write
-  # discussions: write
-  # issues: write
-  # packages: write
-  # pages: write
-  # pull-requests: write
-  # repository-projects: write
-  # security-events: write
-  # statuses: write
-
 jobs:
   relis_unit_testing:
     runs-on: ubuntu-latest
@@ -38,20 +24,20 @@ jobs:
             echo "Docker is not installed, please install Docker in your Github Repository."
           fi
 
-      # - name: Build Docker Image
-      #   run: docker-compose build
-      #   working-directory: relis_deployment
+      - name: Build Docker Image
+        run: docker-compose build
+        working-directory: relis_deployment
 
-      # - name: Run Docker Containers
-      #   run: docker-compose up -d
-      #   working-directory: relis_deployment
+      - name: Run Docker Containers
+        run: docker-compose up -d
+        working-directory: relis_deployment
 
-      # - name: Wait for Application to Start
-      #   run: sleep 10
+      - name: Wait for Application to Start
+        run: sleep 10
 
-      # - name: Set relis-app Container permission
-      #   run: |
-      #     docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
+      - name: Set relis-app Container permission
+        run: |
+          docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
 
       - name: Run Unit test
         run: |
@@ -64,41 +50,47 @@ jobs:
           #   git push
           # }
 
-          # response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
-          # echo $response
-
-          # if [ "$response" == "successful" ]; then
+          response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
+          echo $response
+          
+          if [ "$response" == "successful" ]; then
             echo "The unit test passed. Proceeding with the workflow."
-            git tag last_successful_commit $GITHUB_SHA
-            if git ls-remote --tags origin | grep -q "refs/tags/last_successful_commit"; then
-              git push --delete origin last_successful_commit
-            fi
-            git push origin last_successful_commit
+                  # git tag last_successful_commit $GITHUB_SHA
+                  # if git ls-remote --tags origin | grep -q "refs/tags/last_successful_commit"; then
+                  #   git push --delete origin last_successful_commit
+                  # fi
+                  # git push origin last_successful_commit
 
-          #elif [ "$response" == "failed" ]; then
-            #echo "The unit test failed. Reverting changes to the last successful commit."
-            # git fetch --unshallow
-            #       # git reset --hard last_successful_commit
-            #       # git push --force
-
-            # commit_hash=$(git rev-list -n 1 last_successful_commit)
-            # git config user.email $GITHUB_ACTOR
-            # git config user.name $GITHUB_ACTOR
+          elif [ "$response" == "failed" ]; then
+            echo "The unit test failed. Reverting changes"
+                  # git fetch --unshallow
+                  # git reset --hard last_successful_commit
+                  # git push --force
+                  # commit_hash=$(git rev-list -n 1 last_successful_commit)
+            git config user.email $GITHUB_ACTOR
+            git config user.name $GITHUB_ACTOR
             # git restore .
-            # git revert -X theirs --no-edit $commit_hash
-            #       # git revert -X theirs --no-edit <revert_commit_hash>
-            # git push --force
-            
-            #exit 1
+            git stash
+                  # git revert -X theirs --no-edit $commit_hash
+                  # git revert -X theirs --no-edit <revert_commit_hash>
+                  # git push --force
+            # git revert -X theirs --no-edit $GITHUB_SHA
+            # git push
+            exit 1
 
-      #     else
-      #       echo "The unit test has an error. Reverting changes to the last successful commit."
-      #       #revert_changes
-      #       exit 1
-      #     fi
+          else
+            echo "The unit test has an error. Reverting changes"
+            git config user.email $GITHUB_ACTOR
+            git config user.name $GITHUB_ACTOR
+                  # git restore .
+            git stash
+            git revert -X theirs --no-edit $GITHUB_SHA
+            git push
+            exit 1
+          fi
 
-      # - name: Stop all running Docker Containers
-      #   run: docker stop $(docker ps -q)
+      - name: Stop all running Docker Containers
+        run: docker stop $(docker ps -q)
 
   
 
