commit443

diff --git a/.github/workflows/relis_unit_test.yml b/.github/workflows/relis_unit_test.yml
--- a/.github/workflows/relis_unit_test.yml
+++ b/.github/workflows/relis_unit_test.yml
@@ -86,8 +86,8 @@ jobs:
           elif [ "$response" == "failed" ]; then
             echo "The unit test failed. Reverting changes to the last successful commit."
                   # last_successful_commit=$(cat last_successful_commit.txt)
-                  # git config user.email $GITHUB_ACTOR
-                  # git config user.name $GITHUB_ACTOR
+            git config user.email $GITHUB_ACTOR
+            git config user.name $GITHUB_ACTOR
                   # git restore .
             git fetch --unshallow
                   # git revert -X theirs --no-edit $last_successful_commit
@@ -96,14 +96,14 @@ jobs:
             git push --force
             exit 1
 
-          else
-            echo "The unit test has an error. Reverting changes to the last successful commit."
-            revert_changes
-            exit 1
-          fi
+          # else
+          #   echo "The unit test has an error. Reverting changes to the last successful commit."
+          #   revert_changes
+          #   exit 1
+          # fi
 
-      - name: Stop all running Docker Containers
-        run: docker stop $(docker ps -q)
+      # - name: Stop all running Docker Containers
+      #   run: docker stop $(docker ps -q)
 
   
 
