commit573

diff --git a/.github/workflows/relis_unit_test.yml b/.github/workflows/relis_unit_test.yml
--- a/.github/workflows/relis_unit_test.yml
+++ b/.github/workflows/relis_unit_test.yml
@@ -22,21 +22,19 @@ jobs:
             echo "Docker is not installed, please install Docker in your Github Repository."
           fi
 
-      # - name: Build Docker Image
-      #   run: docker-compose build
-      #   working-directory: relis_deployment
+      - name: Build Docker Image
+        run: docker-compose build
+        working-directory: relis_deployment
 
-      # - name: Run Docker Containers
-      #   run: docker-compose up -d
-      #   working-directory: relis_deployment
+      - name: Run Docker Containers
+        run: docker-compose up -d
+        working-directory: relis_deployment
 
-      # - name: Wait for Application to Start
-      #   run: sleep 10
+      - name: Wait for Application to Start
+        run: sleep 10
 
-      # - name: Set relis-app Container permission
-      #   run: |
-      #     docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
-      #     docker exec relis-app chmod -R 777 /u/relis/public_html/workspace/dslforge_workspace/
+      - name: Set relis-app Container permission
+        run: docker exec relis-app chmod -R 777 /u/relis/public_html/relis_app/
 
       - name: Run Unit test
         run: |
@@ -49,12 +47,12 @@ jobs:
           #   git push
           # }
 
-          # response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
+          response=$(php -r " echo file_get_contents('http://localhost:8083/test/unit_test/relis_unit_test/last_result');")
           
-          # if [ "$response" == "successful" ]; then
-          #   echo "The unit test passed. Proceeding with the workflow."
+          if [ "$response" == "successful" ]; then
+            echo "The unit test passed. Proceeding with the workflow."
 
-          # elif [ "$response" == "failed" ]; then
+          elif [ "$response" == "failed" ]; then
             echo "The unit test failed. Reverting changes"
                   # git config user.email $GITHUB_ACTOR
                   # git config user.name $GITHUB_ACTOR
@@ -69,15 +67,15 @@ jobs:
                     -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     https://api.github.com/repos/$GITHUB_ACTOR/$(basename $GITHUB_REPOSITORY)/actions/workflows/main.yml/dispatches \
                     -d '{"ref":"main"}'
-            # exit 1
+            exit 1
 
-      ##     else
-      #       echo "The unit test has an error. Reverting changes"
-      #       exit 1
-      #     fi
+          else
+            echo "The unit test has an error. Reverting changes"
+            exit 1
+          fi
 
-      # - name: Stop all running Docker Containers
-      #   run: docker stop $(docker ps -q)
+      - name: Stop all running Docker Containers
+        run: docker stop $(docker ps -q)
 
   
 
@@ -147,3 +145,4 @@ jobs:
                   # git config user.name $GITHUB_ACTOR
                   # git restore .
                                     # git revert -X theirs --no-edit $last_successful_commit
+    # docker exec relis-app chmod -R 777 /u/relis/public_html/workspace/dslforge_workspace/
